# Generated by Django 2.2.2 on 2019-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('friend_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='make_friends_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.CharField(max_length=100)),
                ('to_id', models.CharField(max_length=100)),
                ('handled', models.IntegerField(default=0)),
                ('add_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='off_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.IntegerField()),
                ('from_id', models.CharField(max_length=100)),
                ('to_id', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('is_read', models.IntegerField(default=0)),
                ('msg_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('public_key', models.TextField()),
                ('ip_address', models.CharField(max_length=20, null=True)),
                ('is_online', models.IntegerField(default=0)),
                ('have_off_msg', models.IntegerField(default=0)),
                ('have_friends_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
