# Generated by Django 2.2.2 on 2019-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='off_msg',
            old_name='data',
            new_name='msg_enc',
        ),
        migrations.RemoveField(
            model_name='off_msg',
            name='msg_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AlterField(
            model_name='friends',
            name='friend_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='make_friends_requests',
            name='from_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='make_friends_requests',
            name='to_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='off_msg',
            name='from_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='off_msg',
            name='to_id',
            field=models.EmailField(max_length=254),
        ),
    ]
